### ISSUE TITLE
What Java IDE are you using?

### ISSUE THREAD

**Issue by pistolNS** [000JustMe/PewCrypt#1]
I tried to build and make a "Runnable jar file" using Eclipse but I get one error when I try to open the jar file.
`Error: Could not find or load main class PewCrypt.jar`

I tried a few "fixes" found on the internet but without success. I'm a newbie when it comes to java.

**Comment by 000JustMe** [comment]
Try: `java -jar PewCrypt.jar`

**Comment by pistolNS** [comment]
Now the program starts up but it doesn't encrypt anything. :(
I don't know what am I doing wrong...

**Comment by 000JustMe** [comment]
You need to remove the two back slashes in-front of the statement on line 24 of Main.java 
Before: `// crypto.ProcessFile(f);`
After: `crypto.ProcessFile(f);`

**Comment by pistolNS** [comment]
Wow, I feel so stupid right now..
Thank you very much, dude.

**Comment by valerierx** [comment]
I'm also using Eclipse but I can't compile

**Comment by pistolNS** [comment]
> 
> 
> I'm also using Eclipse but I can't compile

Since I struggled a bit to make it work, thanks to google and the creator of this project, Here's what I did to make it work:
1. Open up Eclipse and click on "File" then "Open Projects from File System" and add the "Encryptor" folder.
2. Click on "Project". Make sure you have "Build automatically" option checked.
3. Click on "Project" again and then choose "Properties", click on "Java Build Path" then "Libraries",
"Add external class folder" and then select bin\main folder (containing .class files), then hit "Apply and close"
4. I suppose you have to run it once as "1 Java Application"
5. Then right-click on "Encryptor" in "Package Explorer" and select "Export",
drop down "Java" menu and select "Runnnable JAR file"
6. Select "Main - Encryptor" and Save it.
Make sure you have `// crypto.ProcessFile(f);` commented out if you're testing it on your main computer.

To run it you can use cmd "java -jar PewCrypt.jar" as suggested by https://github.com/000JustMe or you can use the longer path to your java, example: `"C:\Program Files\Java\jre1.8.0_202\bin\java.exe" -jar PewCrypt.jar`
Or make a new batch file and add in those parameters.

And if you want you can convert your .jar file to .exe using Launch4j.
Good luck!
